name: "Read YAML"
description: "This is a NodeJS action to read YAML configuration files."
inputs:
  config:
    description: "The configuration file name."
    required: true
    default: ""
outputs:
  location:
    description: "The location of the Azure resources."
  namespace:
    description: "The namespace for the Azure resources. Also known as the resource prefix."
  postfix:
    description: "The postfix for the Azure resources."
  environment:
    description: "The environment of the Azure Machine Learning Workspace. Typically, either dev or prod."
  enable_aml_computecluster:
    description: "Whether to enable Azure Machine Learning Compute Cluster."
  enable_monitoring:
    description: "Whether to enable Azure Machine Learning Workspace monitoring."
  resource_group:
    description: "The resource group for the Azure resources."
  aml_workspace:
    description: "The Azure Machine Learning Workspace name."
  bep:
    description: "The batch endpoint name."
  oep:
    description: "The online endpoint name."
  terraform_version:
    description: "The Terraform version."
  terraform_workingdir:
    description: "The working directory of the Terraform State."
  terraform_st_location:
    description: "The location of the Terraform State."
  terraform_st_resource_group:
    description: "The Resource Group of the Terraform State."
  terraform_st_storage_account:
    description: "The Azure Storage Account of the Terraform State."
  terraform_st_container_name:
    description: "The container name of the Terraform State."
  terraform_st_key:
    description: "The storage key of the Terraform State."
runs:
  using: "node20"
  main: "index.js"
