name: create-endpoint

on:
  workflow_call:
    inputs:
      endpoint_file:
        required: true
        type: string
      endpoint_postfix:
        required: true
        type: string
      endpoint_type:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string

    secrets:
      creds:
        required: true

jobs:
  create-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.creds }}
          enable-AzPSSession: true

      - name: Install or Update Azure ML Extension
        run: |
          az extension add -n ml -y || az extension update -n ml -y

      - name: Get Endpoint Name
        # 1. Extract the name of the endpoint from endpoint_file (YAML) using grep and sed
        # 2. Export the endpoint name to an environment variable
        run: |
          ENDPOINT_NAME=$(grep 'name:' "${{ github.workspace }}/${{ inputs.endpoint_file }}" | sed 's/.*name: \(\.\.\/\)*//')
          echo "ENDPOINT_NAME=$ENDPOINT_NAME" >> $GITHUB_ENV

      # Check if the endpoint already exists
      - name: Check if Endpoint Exists
        run: |
          az ml ${{ inputs.endpoint_type }}-endpoint show \
            --name "${ENDPOINT_NAME}-${{ inputs.endpoint_postfix }}" \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --output none && echo "ENDPOINT_EXISTS=true" >> $GITHUB_ENV || echo "ENDPOINT_EXISTS=false" >> $GITHUB_ENV

      - name: Create Endpoint from File
        if: env.ENDPOINT_EXISTS == 'false'
        run: |
          az ml ${{ inputs.endpoint_type }}-endpoint create \
            --name "${ENDPOINT_NAME}-${{ inputs.endpoint_postfix }}" \
            -f ${{ github.workspace }}/${{ inputs.endpoint_file }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }}

      - name: Update Existing Endpoint
        if: env.ENDPOINT_EXISTS == 'true'
        # az ml ${{ inputs.endpoint_type }}-endpoint update \
        #   --name "${ENDPOINT_NAME}-${{ inputs.endpoint_postfix }}" \
        #   -f ${{ github.workspace }}/${{ inputs.endpoint_file }} \
        #   --resource-group ${{ inputs.resource_group }} \
        #   --workspace-name ${{ inputs.workspace_name }}
        run: echo "Endpoint exists."
