name: register-dataset

on:
  workflow_call:
    inputs:
      data_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      file_type:
        required: false
        default: ""
        type: string
      name:
        required: true
        type: string

    secrets:
      creds:
        required: true

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.creds }}
          enable-AzPSSession: true

      - name: Install or Update Azure ML Extension
        run: |
          az extension add -n ml -y || az extension update -n ml -y

      # Step to parse the data file path from data_file (YAML file) and calculate its MD5 hash
      - name: Calculate MD5 Checksum of Dataset File
        id: calculate-hash
        # 1. Extract the path to the actual data file from data_file (YAML) using grep and sed
        # 2. Adjust the path based on the GitHub workspace structure
        # 3. Calculate the MD5 hash of the actual data file and store it in an environment variable
        run: |
          DATA_PATH=$(grep 'path:' "${{ github.workspace }}/${{ inputs.data_file }}" | sed 's/.*path: \(\.\.\/\)*//')
          FULL_DATA_PATH="${{ github.workspace }}/${DATA_PATH}"
          DATA_HASH=$(md5sum "$FULL_DATA_PATH" | awk '{ print $1 }')
          echo "DATA_HASH=$DATA_HASH" >> $GITHUB_ENV

      # Check if a dataset with the same DATA_HASH tag already exists
      - name: Check for Existing Dataset
        # Query Azure ML for existing datasets with the specified name and hash tag
        run: |
          DATASET_EXISTS=$(az ml data list \
            --name ${{ inputs.name }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --query "[?tags.DATA_HASH=='${{ env.DATA_HASH }}'] | length(@)" || echo "0")
          echo "DATASET_EXISTS=$DATASET_EXISTS" >> $GITHUB_ENV

      # The difference between registering dataset from file and registering dataset as a job
      # is the definition of the data_file (usually a YAML file with a defined schema). In the former case,
      # the schema specifies a simple dataset, usually an existing dataset without the need for further
      # transformation or modification. Whereas, in the latter case, the schema specifies a slightly more
      # complex dataset where a job can be created to processes data before registration, allowing for
      # transformations and preprocessing — the command for preprocess is defined in the YAML file.

      # Conditionally register the dataset only if no existing dataset with the same hash is found
      - name: Register Dataset from File
        if: ${{ inputs.file_type == '' && env.DATASET_EXISTS == '0' }}
        run: |
          echo "Registering dataset from file: ${{ inputs.data_file }}"
          az ml data create \
            --file ${{ github.workspace }}/${{ inputs.data_file }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --name ${{ inputs.name }}
          echo "Dataset '${{ inputs.name }}' registered successfully."
     
      # Add tag to the newly registered dataset
      - name: Add Tag to Dataset
        if: ${{ inputs.file_type == '' && env.DATASET_EXISTS == '0' }}
        run: |
          echo "Adding tag: 'DATA_HASH=${{ env.DATA_HASH }}' to dataset: '${{ inputs.name }}'."
          az ml data update \
            --name ${{ inputs.name }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --set tags.DATA_HASH=${{ env.DATA_HASH }}
          echo "Tag: 'DATA_HASH=${{ env.DATA_HASH }}' added to dataset: '${{ inputs.name }}'."

      # Conditionally create the job only if no existing dataset with the same hash is found
      - name: Register Dataset as Job
        if: ${{ inputs.file_type != '' && env.DATASET_EXISTS == '0' }}
        run: |
          echo "Registering dataset as a job with file type: ${{ inputs.file_type }}"
          az ml job create \
            --file ${{ github.workspace }}/${{ inputs.data_file }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }}
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
          echo "Job created successfully with file: ${{ inputs.data_file }}"

      # Wait for the job to complete
      - name: Wait for Job Completion
        if: ${{ inputs.file_type != '' && env.DATASET_EXISTS == '0' }}
        run: |
          echo "Waiting for job completion: ${{ env.JOB_ID }}"
          az ml job wait \
            --name ${{ env.JOB_ID }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }}

      # Retrieve the output dataset ID from the job, assuming the job outputs a dataset
      - name: Get Output Dataset ID
        if: ${{ inputs.file_type != '' && env.DATASET_EXISTS == '0' }} 
        run: |
          OUTPUT_DATASET_ID=$(az ml job show --name ${{ env.JOB_ID }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --query "outputs.processed_data.uri" -o tsv)
          echo "OUTPUT_DATASET_ID=$OUTPUT_DATASET_ID" >> $GITHUB_ENV

      # Add tags to the output dataset created by the job
      - name: Add Tag to Output Dataset
        if: ${{ inputs.file_type != '' && env.DATASET_EXISTS == '0' && env.OUTPUT_DATASET_ID != '' }}
        run: |
          echo "Adding tag: 'DATA_HASH=${{ env.DATA_HASH }}' to output dataset: ${{ env.OUTPUT_DATASET_ID }}"
          az ml data update \
            --ids ${{ env.OUTPUT_DATASET_ID }} \
            --resource-group ${{ inputs.resource_group }} \
            --workspace-name ${{ inputs.workspace_name }} \
            --set tags.DATA_HASH=${{ env.DATA_HASH }}
          echo "Tag: 'DATA_HASH=${{ env.DATA_HASH }}' added to output dataset."

      # Skip registration if the dataset with the same hash already exists
      - name: Skip Registration
        if: ${{ env.DATASET_EXISTS != '0' }}
        run: echo "Dataset with the same MD5 checksum hash '${{ env.DATA_HASH }}' already exists. Skipping registration."
